apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customnspsp:privileged
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - vmware-system-privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: customnspsp:psp:privileged
roleRef:
  kind: ClusterRole
  name: customnspsp:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:custom # allow for all service accounts in namespace called 'custom'
  apiGroup: rbac.authorization.k8s.io
# Authorize specific service accounts (not recommended):
# - kind: ServiceAccount
#   name: jenkins-sa
#   namespace: jenkins