---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-app-manager
rules:
  - apiGroups: ["argoproj.io"]  # API group for ArgoCD resources
    resources: ["applications", "applicationsets"]  # ArgoCD resources
    verbs: ["get", "list", "create", "update", "delete"]  # Permitted actions
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]  # Access to certain resources in the namespace (optional)
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user1-argocd-app-manager
  namespace: anahid  # The namespace where the Role exists
subjects:
  - kind: User
    name: user1  # The user to be granted the permissions
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: argocd-app-manager  # The Role that defines the permissions
  apiGroup: rbac.authorization.k8s.io