# First stage: complete build environment
FROM maven:3-openjdk-18 AS builder

# add pom.xml and source code
ADD ./pom.xml pom.xml
ADD ./src src/

# package jar
RUN mvn clean package

# Second stage: minimal runtime environment
FROM eclipse-temurin:18-jre-alpine

# copy jar from the first stage
COPY --from=builder target/simplegreetings-0.0.1-SNAPSHOT.jar simplegreetings-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar", "simplegreetings-0.0.1-SNAPSHOT.jar"]