apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-greetings
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: ssh://git@github.com/alinahid477/simple-greetings.git
      ref:
        branch: main