---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-greetings-byargo
  namespace: user1
spec:
  selector:
    matchLabels:
      app: simple-greetings-byargo
  template:
    metadata:
      labels:
        app: simple-greetings-byargo
    spec:
      imagePullSecrets:
      - name: alitestseverything-quay-secret
      containers:
      - name: simple-greetings-byargo
        image: quay.io/alitestseverything/simple-greetings:2.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: GREETING_TEXT
          value: hello from user1
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: simple-greetings
#   namespace: anahid
# spec:
#   ports:
#   - port: 80
#     targetPort: 8080
#   selector: 
#     app: simple-greetings
#   type: LoadBalancer